### ISSUE TITLE
Ability to use other RDBMS than Postgresql

### ISSUE THREAD

**Issue by maver1ck** [puckel/docker-airflow#200]
Hi,
I'd like to use MySQL with this dockerfile. 
I can create PR but this will probably break backward compatibility 
(we should change ENV variables from POSTGRES_* to DB_*)

WDYT ?

**Comment by danrubenstein** [comment]
Not the maintainer, but maybe instead of a PR, a faster approach just to get your own MySQL airflow install off the ground is to build your own dockerfile that mounts off of this one and then create a custom entrypoint file that has the MySQL variables that you want?
```
#!/usr/bin/env bash
# my_entrypoint.sh

# Set the custom MySQL variables
export AIRFLOW__CORE__SQL_ALCHEMY_CONN="mysql+mysqldb://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_DB}"
...
# Set some more variables
...
# Run the airflow commands
```

And then create your own dockerfile that copies the script and sets your custom script as the entrypoint:
```
# Custom Dockerfile
FROM puckel/docker-airflow

CP my_entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]
```

Although if you want to go the PR route on this repository, don't let me stop you. I would guess that breaking backward compatibility here might be a hard sell though.

**Comment by danrubenstein** [comment]
Maybe also take a look at #149 for inspiration.

**Comment by maver1ck** [comment]
@danrubenstein 
I created PR.
WDYT?

**Comment by maver1ck** [comment]
Closing.
